### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Chaleeshadow** [planetarium/planet-clicker#35]
Hi, I am new to the blockchain and basic network, I have a question about this project.  
What is public key? and where to get it?

**Comment by jckdotim** [comment]
@Chaleeshadow sorry for late response. You can learn about public key concept here. https://academy.binance.com/en/articles/what-is-public-key-cryptography

**Comment by jckdotim** [comment]
I'll close this issue because issues feature is not for Q&A.
